name: CI

on:
  workflow_dispatch:
    inputs:
      data:
        description: "Input data"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run echo
        run: echo "${{ github.event.inputs.data }}"
